### ISSUE TITLE
NullPointerException when using "send()" method

### ISSUE THREAD

**Issue by whirvis** [Doridian/SteamMobileLib#1]
In the Main class to test the program, everything seems to work but when it calls the method "handler.logon()" a NullPointerException is thrown.

Stack trace:
Exception in thread "main" java.lang.NullPointerException
    at de.doridian.steammobile.connection.MessageHandler.logon(MessageHandler.java:37)
    at de.doridian.steammobile.test.Main.connect(Main.java:85)
    at de.doridian.steammobile.test.Main.main(Main.java:34)

**Comment by Doridian** [comment]
Sadly steam removed the method for logging in.
It now uses some integrated OAuth via a WebView making it really hard (almost impossible thanks to their CAPTCHA) to do this as a CLI app :(
